### ISSUE TITLE
Inconsistency between documentation and OpenAPI spec for Gifting Packages

### ISSUE THREAD

**Issue by ploxxxy** [tebexio/TebexHeadless-OpenAPI#1]
**Description:**

I'm encountering an issue when attempting to gift a package to another player using Headless API

**Expected Behavior:**

According to both the [official docs](https://docs.tebex.io/developers/headless-api/adding-packages#gifting-a-package-to-another-player) and the [Postman collection](https://documenter.getpostman.com/view/10912536/2s9XxvTEmh#4a626370-e20c-497a-8aee-a7bdd478f4ae), gifting should be possible by including the `target_username_id` field in the request body.

**Actual Behavior:**

However, the latest version of your OpenAPI spec has no mention of gifting, or the "target_username_id" field. Despite this, attempting to send a request with said field still results in a `The provided username that should receive the gift is invalid` error message:

![image](https://github.com/user-attachments/assets/103e38a4-a8d3-49a5-95fc-8451f458e399)

**Additional Info:**

* This username is valid ([NameMC](https://namemc.com/profile/YukiKawaii.2))
* My webstore is set to Minecraft (Offline/Geyser)
* Gifting works on the Tebex-hosted frontend

Could you clarify if gifting is currently supported?

**Comment by WildBamaBoy** [comment]
This should definitely be working - to me it is strange that we're seeing "User not found" in the error detail yet this is a valid username. I will follow up with our API team to see why this is happening.

**Comment by WildBamaBoy** [comment]
This is due to `target_username_id` expecting a UUID for the user.

We have recently updated Headless API to allow for a `target_username` instead, which should achieve what you're trying to do:

```
{
    "package_id": "6366436",
    "target_username": "YukiKawaii"
}
```

As this is a bit of a special case when using the add packages endpoints, this may not necessarily be present in the OpenAPI documentation. We always recommend reviewing our full documentation here for and special actions or otherwise that can be performed with the API: https://docs.tebex.io/developers/headless-api/overview
